name: Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        path: DevelopmentEnvironment

    - name: Create Archive
      run: |
        Compress-Archive -Path DevelopmentEnvironment -DestinationPath DevelopmentEnvironment.zip

    - name: Publish Archive
      id: create_release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: false
        title: "DevelopmentEnvironment"
        files: |
          DevelopmentEnvironment.zip
